# vim: set ft=ansible
---

# Implement your Workload deployment tasks here

- name: Delete the Open Data Hub Operator
  k8s:
    state: absent
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: "opendatahub-operator.v0.6.1"
        namespace: "{{ operator_namespace }}"

- name: Delete the Open Data Hub Operator Subscription
  k8s:
    state: absent
    namespace: "{{ operator_namespace }}"
    definition: "{{ lookup('template', 'subscription.yaml.j2' ) }}"

- name: Delete the Open Data Hub project
  k8s:
    state: absent
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
